python predict_session_day.py --trial_type "animate" --task "memory"
python predict_session_day.py --trial_type "animate" --task "visual"
python predict_session_day.py --trial_type "animate" --task "combined"
python predict_session_day.py --trial_type "inanimate" --task "memory"
python predict_session_day.py --trial_type "inanimate" --task "visual"
python predict_session_day.py --trial_type "inanimate" --task "combined"

python predict_session_number.py --trial_type "animate" --task "memory"
python predict_session_number.py --trial_type "animate" --task "visual"
python predict_session_number.py --trial_type "animate" --task "combined"
python predict_session_number.py --trial_type "inanimate" --task "memory"
python predict_session_number.py --trial_type "inanimate" --task "visual"
python predict_session_number.py --trial_type "inanimate" --task "combined"

python predict_trial_number.py --trial_type "inanimate" --task "memory"
python predict_trial_number.py --trial_type "inanimate" --task "visual"
python predict_trial_number.py --trial_type "inanimate" --task "combined"
python predict_trial_number.py --trial_type "animate" --task "memory"
python predict_trial_number.py --trial_type "animate" --task "visual"
python predict_trial_number.py --trial_type "animate" --task "combined"
